"""Render a resolved profile into a `CLAUDE.md` file.

Design goals:
- **Deterministic & idempotent**: same inputs → byte-identical output. Golden
  tests pin this; team renders shouldn't churn git history.
- **Native to Claude Code**: emit a single Markdown file at either user
  (`~/.claude/CLAUDE.md`) or project (`<repo>/CLAUDE.md`) scope. The
  `@import` syntax is supported but only used when explicitly requested,
  to keep the v1 output a single file that's easy to review.
- **Self-describing**: a generation banner records the source profiles and
  the schema version so a human reading the rendered file knows where it
  came from and not to hand-edit it.

The renderer takes the output of `merger.merge_profiles` so conflicts have
already been resolved (or the caller has chosen to render with conflicts
unresolved — in which case team values stand and a warning section is
included).
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any

from . import __version__
from .merger import MergeResult
from .schema import Entry, Section

if TYPE_CHECKING:  # avoid runtime cycle / keep skills optional
    from .skills.resolver import SkillSet

# Order in which sections appear in the rendered output. Stable for diff hygiene.
_SECTION_ORDER: tuple[Section, ...] = (
    Section.IDENTITY,
    Section.LANGUAGES,
    Section.TOOLS,
    Section.CODING_STYLE,
    Section.WORKFLOW,
    Section.DOMAIN_KNOWLEDGE,
    Section.DO_NOT,
    Section.FREE_FORM,
)

_SECTION_TITLES: dict[Section, str] = {
    Section.IDENTITY: "Identity",
    Section.LANGUAGES: "Languages",
    Section.TOOLS: "Tools",
    Section.CODING_STYLE: "Coding style",
    Section.WORKFLOW: "Workflow",
    Section.DOMAIN_KNOWLEDGE: "Domain knowledge",
    Section.DO_NOT: "Do NOT",
    Section.FREE_FORM: "Notes",
}


@dataclass(frozen=True)
class RenderContext:
    """Inputs that influence the rendered output but aren't entries themselves."""

    team_owner: str
    personal_owner: str
    # Pass `None` in tests/CI to suppress timestamps and keep output byte-stable.
    generated_at: datetime | None = None


def _content_hash(merge_result: MergeResult) -> str:
    """A short, stable hash of the resolved entries — pinned in the banner so
    reviewers can spot when output is regenerated from identical input."""
    payload = json.dumps(
        [e.model_dump(mode="json") for e in merge_result.resolved],
        sort_keys=True,
        separators=(",", ":"),
    )
    return hashlib.sha256(payload.encode()).hexdigest()[:12]


def _format_value(value: Any) -> str:
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return value
    if isinstance(value, list):
        return "\n".join(f"- {item}" for item in value)
    if isinstance(value, dict):
        return "\n".join(f"- **{k}** — {v}" for k, v in value.items())
    return repr(value)


def _render_entry(entry: Entry) -> str:
    lines: list[str] = []
    title = entry.key.replace("_", " ")
    lock_tag = " 🔒" if entry.lock else ""
    lines.append(f"#### {title}{lock_tag}")
    body = _format_value(entry.value)
    # Single-line scalars sit better as plain text; lists/maps already have newlines.
    if "\n" in body or body.startswith("- "):
        lines.append(body)
    else:
        lines.append(body)
    if entry.rationale:
        lines.append(f"\n_Rationale: {entry.rationale}_")
    return "\n".join(lines)


def _banner(ctx: RenderContext, merge_result: MergeResult) -> str:
    ts = "" if ctx.generated_at is None else ctx.generated_at.isoformat()
    lines = [
        "<!--",
        f"  Generated by sic v{__version__}. DO NOT EDIT — edit the source profile YAML instead.",
        f"  team    : {ctx.team_owner}",
        f"  personal: {ctx.personal_owner}",
        f"  content : sha256:{_content_hash(merge_result)}",
    ]
    if ts:
        lines.append(f"  at      : {ts}")
    lines.append("-->")
    return "\n".join(lines)


def render_claude_md(
    merge_result: MergeResult,
    ctx: RenderContext,
    skill_set: "SkillSet | None" = None,
) -> str:
    """Render a resolved merge result as a CLAUDE.md string.

    If ``skill_set`` is provided and non-empty, an "Available skills" table is
    appended so the agent knows what skill bundles exist alongside the
    profile. Pass ``None`` (the default) to keep output byte-stable for
    callers that don't manage skills.
    """
    by_section: dict[Section, list[Entry]] = {s: [] for s in _SECTION_ORDER}
    for e in merge_result.resolved:
        by_section[e.section].append(e)

    parts: list[str] = [_banner(ctx, merge_result), ""]
    parts.append(f"# Team memory — {ctx.team_owner} (overlay: {ctx.personal_owner})")
    parts.append("")
    parts.append(
        "This file is compiled by [sharing-is-caring](https://example.invalid) "
        "from a team profile plus a personal overlay. Conflicts surface via "
        "`sic conflicts`."
    )
    parts.append("")

    for section in _SECTION_ORDER:
        entries = by_section[section]
        if not entries:
            continue
        parts.append(f"## {_SECTION_TITLES[section]}")
        parts.append("")
        # Entries within a section are already sorted by `key` (merger sorts globally).
        for entry in entries:
            parts.append(_render_entry(entry))
            parts.append("")

    if skill_set is not None and skill_set.installed:
        parts.append("## Available skills")
        parts.append("")
        parts.append(
            "These skill bundles are installed locally and available to the "
            "agent. Run `sic skills show NAME` to view one."
        )
        parts.append("")
        parts.append("| Name | Version | Scope | Description |")
        parts.append("| --- | --- | --- | --- |")
        for inst in skill_set.installed:
            m = inst.skill.manifest
            lock = " 🔒" if m.lock else ""
            desc = " ".join(m.description.split())  # collapse whitespace
            parts.append(
                f"| `{m.name}`{lock} | {m.version} | {inst.scope.value} | {desc} |"
            )
        parts.append("")

    if merge_result.conflicts:
        parts.append("## ⚠️ Unresolved conflicts")
        parts.append("")
        parts.append(
            "The following entries are shown with the **team** value because a "
            "conflict has not yet been resolved. Run `sic conflicts` to triage."
        )
        parts.append("")
        for c in merge_result.conflicts:
            parts.append(
                f"- `{c.identifier}` — {c.reason.value} "
                f"(team: `{c.team_entry.value!r}` vs personal: `{c.personal_entry.value!r}`)"
            )
        parts.append("")

    if skill_set is not None and skill_set.conflicts:
        parts.append("## ⚠️ Unresolved skill conflicts")
        parts.append("")
        for c in skill_set.conflicts:
            parts.append(
                f"- `{c.name}` — team@{c.team_version} is locked; "
                f"personal@{c.personal_version} was ignored"
            )
        parts.append("")

    return "\n".join(parts).rstrip() + "\n"


def write_claude_md(text: str, target_path: Path) -> Path:
    target_path.parent.mkdir(parents=True, exist_ok=True)
    target_path.write_text(text)
    return target_path


def resolve_target_path(target: str, project_root: Path) -> Path:
    """Translate `--target user|project` into a filesystem path."""
    if target == "user":
        return Path.home() / ".claude" / "CLAUDE.md"
    if target == "project":
        return project_root / "CLAUDE.md"
    raise ValueError(f"unknown render target: {target!r} (expected 'user' or 'project')")
